{% set version = "1.23.0" %}

package:
  name: grpcio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/grpcio/grpcio-{{ version }}.tar.gz
  sha256: 3cd3d99a8b5568d0d186f9520c16121a0f2a4bcad8e2b9884b76fb88a85a7774
  patches:
    - windows_staticlink.patch                # [win]
    - windows_ssl_lib_names.patch             # [win and openssl != "1.1.1" and openssl != "1.1.1a"]
    - windows_ssl_lib_names_openssl111.patch  # [win and (openssl == "1.1.1" or openssl == "1.1.1a")]
    - extra_include_and_lib_dirs.patch        # [win]

build:
  number: 1
  # protobuf does not support Visual C++ 2008, skip windows py27
  skip: True  # [win and vc<10]

requirements:
  build:
    - {{ compiler('c') }}     # [not win]
    - {{ compiler('cxx') }}   # [not win]
  host:
    - python
    - pip
    - cython
    - six >=1.5.2
    - futures >=2.2.0   # [py27]
    - enum34 >=1.0.4    # [py27]
    - zlib
    - openssl
    - c-ares            # [unix]
    - m2w64-toolchain   # [win]
    - libpython         # [win]
  run:
    - python
    - setuptools
    - six >=1.5.2
    - futures >=2.2.0   # [py27]
    - enum34 >=1.0.4    # [py27]
    - zlib
    - openssl
    - {{ pin_compatible("c-ares") }}  # [unix]
    - m2w64-gcc-libs   # [win]

test:
  imports:
    - grpc
    - grpc._cython
    - grpc._cython._cygrpc
    - grpc.beta
    - grpc.framework
    - grpc.framework.common
    - grpc.framework.foundation
    - grpc.framework.interfaces
    - grpc.framework.interfaces.base
    - grpc.framework.interfaces.face

about:
  home: https://grpc.io
  license: Apache 2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  license_family: APACHE
  summary: HTTP/2-based RPC framework

extra:
  recipe-maintainers:
    - ocefpaf
    - jcrist
